[project]
name = "smtp-tlsa-verify"
version = "0.1.0"
description = "A small library, command-line utility and JSON/HTTP service to check DANE/TLSA-RRs against SMTP servers."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dnspython>=2.7.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.5",
    "tox>=4.28.3",
]
